name: Build Android

on: [workflow_dispatch]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
  
      - name: Import Android keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          # import keystore 
          echo -n "$KEYSTORE_BASE64" | base64 --decode > android.keystore

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Cordova Android platform
        run: cordova platform add android@12.0.0

      - name: Add cordova-plugin-androidx-adapter
        run: cordova plugin add cordova-plugin-androidx-adapter@1.1.3

      - name: Add cordova-plugin-inappbrowser
        run: cordova plugin add cordova-plugin-inappbrowser

      - name: Build Android release APK
        run: cordova build android --release -- --keystore=android.keystore --storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} --alias=${{ secrets.ANDROID_KEYSTORE_ALIAS }} --password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} --packageType=apk

      - name: Upload Android release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app-release-apk
          path: platforms/android/app/build/outputs/apk/release/app-release.apk

      - name: Build Android App Bundle
        run: cordova build android --release -- --keystore=android.keystore --storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} --alias=${{ secrets.ANDROID_KEYSTORE_ALIAS }} --password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} --packageType=bundle

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-app-release-aab
          path: platforms/android/app/build/outputs/bundle/release/app-release.aab
  
